# Generated by Django 4.2.7 on 2025-11-08 00:39

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('admin', 'Administrator'), ('trader', 'Trader'), ('viewer', 'Viewer')], default='trader', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='custom_user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(choices=[('binance', 'Binance'), ('coinbase', 'Coinbase'), ('kraken', 'Kraken'), ('kucoin', 'KuCoin'), ('okx', 'OKX'), ('huobi', 'Huobi'), ('bybit', 'Bybit')], max_length=50)),
                ('label', models.CharField(blank=True, help_text='A friendly name to identify this API key', max_length=100, null=True)),
                ('api_key', models.TextField(help_text='The API key from the exchange')),
                ('secret_key', models.TextField(help_text='The secret key from the exchange')),
                ('passphrase', models.TextField(blank=True, help_text='Passphrase (required for some exchanges like OKX, Coinbase, KuCoin)', null=True)),
                ('is_encrypted', models.BooleanField(default=False, help_text='Whether the keys are encrypted in the database')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this API key is active for trading')),
                ('is_validated', models.BooleanField(default=False, help_text='Whether the API key has been validated with the exchange')),
                ('permissions', models.JSONField(default=list, help_text="List of allowed permissions: ['read', 'trade']")),
                ('requests_per_minute', models.IntegerField(default=60, help_text='Maximum requests per minute')),
                ('last_request_time', models.DateTimeField(blank=True, help_text='Last API request time', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used', models.DateTimeField(blank=True, help_text='Last time this API key was used', null=True)),
                ('last_validated', models.DateTimeField(blank=True, help_text='Last time this API key was validated', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'db_table': 'api_keys',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'exchange')},
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_tolerance', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('max_daily_loss', models.DecimalField(decimal_places=2, default=1000.0, max_digits=10)),
                ('max_position_size', models.DecimalField(decimal_places=2, default=5000.0, max_digits=10)),
                ('preferred_exchanges', models.JSONField(default=list)),
                ('notification_preferences', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='APIKeyUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text="Action performed: 'price_check', 'order_place', etc.", max_length=50)),
                ('endpoint', models.CharField(help_text='API endpoint or method called', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True, help_text='Whether the action was successful')),
                ('response_time', models.DecimalField(decimal_places=3, help_text='Response time in seconds', max_digits=8)),
                ('error_message', models.TextField(blank=True, help_text='Error message if failed', null=True)),
                ('request_data', models.JSONField(blank=True, help_text='Request data (sanitized)', null=True)),
                ('response_data', models.JSONField(blank=True, help_text='Response data (sanitized)', null=True)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='users.apikey')),
            ],
            options={
                'verbose_name': 'API Key Usage Log',
                'verbose_name_plural': 'API Key Usage Logs',
                'db_table': 'api_key_usage_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['api_key', 'timestamp'], name='api_key_usa_api_key_dede0b_idx'), models.Index(fields=['action', 'timestamp'], name='api_key_usa_action_85c757_idx'), models.Index(fields=['success', 'timestamp'], name='api_key_usa_success_d5081e_idx')],
            },
        ),
    ]
