# Generated by Django 4.2.7 on 2025-11-12 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('exchange_type', models.CharField(choices=[('cex', 'Centralized Exchange'), ('dex', 'Decentralized Exchange')], default='cex', max_length=10)),
                ('base_url', models.URLField()),
                ('api_documentation', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('trading_fee', models.DecimalField(decimal_places=4, default=0.001, max_digits=6)),
                ('withdrawal_fee', models.JSONField(default=dict)),
                ('rate_limit', models.IntegerField(default=1200)),
                ('precision_info', models.JSONField(default=dict)),
                ('supported_pairs', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Exchange',
                'verbose_name_plural': 'Exchanges',
                'db_table': 'exchanges',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('bid_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('ask_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('last_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('volume_24h', models.DecimalField(decimal_places=8, max_digits=20)),
                ('spread', models.DecimalField(decimal_places=4, max_digits=10)),
                ('timestamp', models.DateTimeField()),
                ('is_fresh', models.BooleanField(default=True)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchanges.exchange')),
            ],
            options={
                'verbose_name': 'Market Data',
                'verbose_name_plural': 'Market Data',
                'db_table': 'market_data',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['symbol', 'timestamp'], name='market_data_symbol_9bb1b2_idx'), models.Index(fields=['exchange', 'symbol'], name='market_data_exchang_159d96_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExchangeCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_validated', models.BooleanField(default=False)),
                ('validation_message', models.TextField(blank=True, null=True)),
                ('last_validation', models.DateTimeField(blank=True, null=True)),
                ('trading_enabled', models.BooleanField(default=False)),
                ('withdrawal_enabled', models.BooleanField(default=False)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.apikey')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchanges.exchange')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exchange Credentials',
                'verbose_name_plural': 'Exchange Credentials',
                'db_table': 'exchange_credentials',
                'unique_together': {('user', 'exchange')},
            },
        ),
    ]
