# Generated by Django 4.2.7 on 2025-10-17 01:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triangle', models.JSONField(default=list)),
                ('entry_amount', models.FloatField()),
                ('exit_amount', models.FloatField()),
                ('profit', models.FloatField()),
                ('profit_percentage', models.FloatField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='executed', max_length=32)),
                ('exchange', models.CharField(default='unknown', max_length=64)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'arbitrage_trade',
                'ordering': ['-timestamp'],
            },
        ),
    ]
