# Generated by Django 4.2.7 on 2025-11-10 11:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArbitrageOpportunityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triangle', models.JSONField(default=list)),
                ('profit_percentage', models.FloatField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('prices', models.JSONField(default=dict)),
                ('steps', models.JSONField(default=list)),
                ('source', models.CharField(default='live', max_length=32)),
            ],
            options={
                'db_table': 'arbitrage_opportunity',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RiskAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('message', models.TextField()),
                ('metric', models.CharField(blank=True, max_length=100, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('threshold', models.FloatField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'risk_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TradeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triangle', models.JSONField(default=list)),
                ('entry_amount', models.FloatField()),
                ('exit_amount', models.FloatField()),
                ('profit', models.FloatField()),
                ('profit_percentage', models.FloatField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='executed', max_length=32)),
                ('exchange', models.CharField(default='unknown', max_length=64)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'arbitrage_trade',
                'ordering': ['-timestamp'],
            },
        ),
    ]
