# Generated by Django 4.2.7 on 2025-11-12 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arbitrage_bot', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RiskAlert',
        ),
    ]
