# Generated by Django 4.2.7 on 2025-10-18 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbitrage_bot', '0003_botconfig_auto_restart_botconfig_enabled_exchanges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botconfig',
            name='trade_size_fraction',
            field=models.FloatField(default=0.01),
        ),
    ]
