# Generated by Django 4.2.7 on 2025-10-27 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbitrage_bot', '0004_botconfig_trade_size_fraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='botconfig',
            name='min_trade_amount',
            field=models.FloatField(default=2.0),
        ),
    ]
