# Generated by Django 4.2.7 on 2025-10-17 03:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('arbitrage_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArbitrageOpportunityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triangle', models.JSONField(default=list)),
                ('profit_percentage', models.FloatField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('prices', models.JSONField(default=dict)),
                ('steps', models.JSONField(default=list)),
                ('source', models.CharField(default='live', max_length=32)),
            ],
            options={
                'db_table': 'arbitrage_opportunity',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='BotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_balance', models.FloatField(default=1000.0)),
                ('max_position_size', models.FloatField(default=100.0)),
                ('max_daily_loss', models.FloatField(default=50.0)),
                ('max_drawdown', models.FloatField(default=20.0)),
                ('min_profit_threshold', models.FloatField(default=0.3)),
            ],
            options={
                'db_table': 'bot_config',
            },
        ),
    ]
