# Generated by Django 4.2.7 on 2025-10-18 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbitrage_bot', '0002_arbitrageopportunityrecord_botconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='botconfig',
            name='auto_restart',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='botconfig',
            name='enabled_exchanges',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='botconfig',
            name='slippage_tolerance',
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name='botconfig',
            name='trading_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
