"""
Base settings for triangularArbitrageBot project.

Generated by 'django-admin startproject' using Django 5.2.5.
"""

import os
import sys
from pathlib import Path
from dotenv import load_dotenv
from datetime import timedelta

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Define project root
PROJECT_ROOT = BASE_DIR.parent

# Ensure static directory exists
STATIC_DIR = BASE_DIR / 'static'
if not STATIC_DIR.exists():
    STATIC_DIR.mkdir(parents=True, exist_ok=True)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-=3)p-=1@+f*@od(h_@r-$q#g++irp&a#x6g3q59qya(d%+58$g')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

AUTH_USER_MODEL = 'users.User'

# Application definition
INSTALLED_APPS = [
     'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third party apps
    'rest_framework',
    'corsheaders',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    
    # Local apps
    'apps.users',
    'apps.arbitrage_bot',
    'apps.notifications',
    #'apps.analytics',
    #'apps.risk_management',
    'apps.trading',
    #'apps.exchanges',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [STATIC_DIR]

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ===== URL CONFIGURATION =====

# URL configuration for triangularArbitrageBot project
URL_PATTERNS = [
    ('admin/', 'admin.site.urls'),
    ('api/arbitrage/', 'apps.arbitrage_bot.urls'),
    ('api/users/', 'apps.users.urls'),
]

# ===== CUSTOM SETTINGS =====

# Trading Configuration
BINANCE_TESTNET = os.getenv('BINANCE_TESTNET', 'False').lower() == 'true'
BINANCE_TLD = os.getenv('BINANCE_TLD', 'com')  # 'com' for international, 'us' for Binance.US

# Increase timeout settings
REQUEST_TIMEOUT = int(os.getenv('REQUEST_TIMEOUT', '30'))
WEBSOCKET_RECONNECT_DELAY = int(os.getenv('WEBSOCKET_RECONNECT_DELAY', '10'))

# CORS settings
CORS_ALLOW_ALL_ORIGINS = os.getenv('CORS_ALLOW_ALL_ORIGINS', 'True').lower() == 'true'
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:5173",  # Vite default port
    "http://127.0.0.1:5173",
]

# Add production domains if needed
if os.getenv('PRODUCTION_DOMAIN'):
    CORS_ALLOWED_ORIGINS.append(os.getenv('PRODUCTION_DOMAIN'))

# CORS methods and headers
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
    ],
    # Use JWT as the primary authentication for API endpoints
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/day',
        'user': '1000/day'
    }
}

# JWT settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    # Ensure refresh tokens are rotated and blacklisted after rotation
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# Celery settings
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# Logging configuration
# Ensure logs directory exists
LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
        'django.server': {
            '()': 'django.utils.log.ServerFormatter',
            'format': '[{server_time}] {message}',
            'style': '{',
        },
        'safe_unicode': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        }
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'django.log',
            'maxBytes': 1024 * 1024 * 5,  # 5 MB
            'backupCount': 5,
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
        'console': {
            'level': 'INFO',  # CHANGED FROM DEBUG TO INFO
            'class': 'logging.StreamHandler',
            'formatter': 'safe_unicode',
        },
        'django.server': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'django.server',
        },
        'arbitrage_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'arbitrage.log',
            'maxBytes': 1024 * 1024 * 10,  # 10 MB
            'backupCount': 5,
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.server': {
            'handlers': ['django.server'],
            'level': 'INFO',
            'propagate': False,
        },
        'apps.arbitrage_bot': {
            'handlers': ['console', 'arbitrage_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'apps.users': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        # Add this to specifically silence autoreload debug messages
        'django.utils.autoreload': {
            'handlers': ['file'],  # Only log to file, not console
            'level': 'WARNING',
            'propagate': False,
        },
    },
}
# Exchange API Keys (use environment variables in production)
EXCHANGE_CONFIG = {
    'binance': {
        'api_key': os.getenv('BINANCE_API_KEY', ''),
        'api_secret': os.getenv('BINANCE_API_SECRET', ''),
        'testnet': BINANCE_TESTNET,
        'tld': BINANCE_TLD,
    },
    'kraken': {
        'api_key': os.getenv('KRAKEN_API_KEY', ''),
        'api_secret': os.getenv('KRAKEN_API_SECRET', ''),
    },
    'coinbase': {
        'api_key': os.getenv('COINBASE_API_KEY', ''),
        'api_secret': os.getenv('COINBASE_API_SECRET', ''),
    },
    'huobi': {
        'access_key': os.getenv('HUOBI_ACCESS_KEY', ''),
        'secret_key': os.getenv('HUOBI_SECRET_KEY', ''),
    },
    'okx': {
        'api_key': os.getenv('OKX_API_KEY', ''),
        'api_secret': os.getenv('OKX_API_SECRET', ''),
        'passphrase': os.getenv('OKX_PASSPHRASE', ''),
    },
}

# Trading limits and configuration
TRADING_CONFIG = {
    'min_profit_threshold': float(os.getenv('MIN_PROFIT_THRESHOLD', '0.5')),  # 0.5%
    'max_position_size': float(os.getenv('MAX_POSITION_SIZE', '1000')),  # $1000
    'daily_loss_limit': float(os.getenv('DAILY_LOSS_LIMIT', '100')),  # $100
    'max_open_trades': int(os.getenv('MAX_OPEN_TRADES', '5')),
    'trade_timeout': int(os.getenv('TRADE_TIMEOUT', '30')),  # seconds
}

# WebSocket configuration
WEBSOCKET_CONFIG = {
    'reconnect_delay': WEBSOCKET_RECONNECT_DELAY,
    'max_reconnect_attempts': int(os.getenv('MAX_RECONNECT_ATTEMPTS', '10')),
    'ping_interval': int(os.getenv('WEBSOCKET_PING_INTERVAL', '30')),
}

# ===== URL PATTERN CONFIGURATION =====
# This provides a centralized way to manage URL patterns
URL_CONFIG = {
    'admin': 'admin/',
    'arbitrage_api': 'api/arbitrage/',
    'users_api': 'api/users/',
    'api_docs': 'api/docs/',
    'api_status': 'api/status/',
}

# API Versioning
API_VERSION = 'v1'
API_PREFIX = f'api/{API_VERSION}'

# ===== DEVELOPMENT SETTINGS =====
# These can be overridden in development.py

# Serve static and media files in development
SERVE_STATIC_IN_DEV = True
SERVE_MEDIA_IN_DEV = True

# Development-specific security settings
DEV_SECURITY_SETTINGS = {
    'SESSION_COOKIE_SECURE': False,
    'CSRF_COOKIE_SECURE': False,
    'SECURE_SSL_REDIRECT': False,
}

# ===== PRODUCTION READY SETTINGS =====
# These can be overridden in production.py

PRODUCTION_SECURITY_SETTINGS = {
    'SESSION_COOKIE_SECURE': True,
    'CSRF_COOKIE_SECURE': True,
    'SECURE_SSL_REDIRECT': True,
    'SECURE_BROWSER_XSS_FILTER': True,
    'SECURE_CONTENT_TYPE_NOSNIFF': True,
    'X_FRAME_OPTIONS': 'DENY',
}

# ===== APPLICATION SPECIFIC SETTINGS =====

# Arbitrage Bot Settings
ARBITRAGE_BOT_CONFIG = {
    'enabled': True,
    'auto_start': False,
    'scan_interval': 60,  # seconds
    'max_concurrent_trades': 3,
    'profit_calculation_method': 'percentage',  # 'percentage' or 'absolute'
    'currency_precision': 8,
    'price_precision': 8,
}

# User Management Settings
USER_MANAGEMENT_CONFIG = {
    'min_password_length': 8,
    'require_email_verification': False,
    'session_timeout': 3600,  # 1 hour in seconds
    'max_login_attempts': 5,
    'lockout_duration': 900,  # 15 minutes in seconds
}

# Notification Settings
NOTIFICATION_CONFIG = {
    'enabled': True,
    'email_notifications': False,
    'push_notifications': False,
    'webhook_url': os.getenv('WEBHOOK_URL', ''),
    'alert_profit_threshold': 1.0,  # 1%
    'alert_loss_threshold': -2.0,  # -2%
}

# Performance Settings
PERFORMANCE_CONFIG = {
    'cache_timeout': 300,  # 5 minutes
    'database_pool_size': 10,
    'max_websocket_connections': 100,
    'request_timeout': 30,
}

# Feature Flags
FEATURE_FLAGS = {
    'advanced_analytics': True,
    'real_time_updates': True,
    'multi_exchange_support': True,
    'risk_management': True,
    'paper_trading': True,
    'backtesting': False,
}

print(f"Base settings loaded - DEBUG: {DEBUG}, ALLOWED_HOSTS: {ALLOWED_HOSTS}")